### PR TITLE
ENH: Allow entities to have aliases

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
Rebased. Will update INCF/pybids#109 to test.

**Comment by tyarkoni** [comment]
Sorry, just getting back to this now. Looks good, though I think the aliases may end up slowing down queries in some cases due to the way things are structured internally. But we can live with that for now. Is this ready to merge?

**Comment by effigies** [comment]
Merging master into INCF/pybids#109 to test.

**Comment by effigies** [comment]
Seems to be failing over there, but not obviously related to this change.

**Comment by tyarkoni** [comment]
Guessing it's a travis hiccup, but re-running to make sure...

**Pull request merged**
