### PR TITLE
Fix natural sort for non-strings

### LINKED ISSUE #80: "natural_sort" does not work if Entity is not string
Related to: https://github.com/INCF/pybids/issues/237

If the dtype of an entity is set to `int`, the natural sort function (used in `get_runs` for example), will fail because it tries to use regex on an int.

### PR DESCRIPTION
**Pull request by adelavega**
Fixes #80 by converting non strings to strings prior to `re.split`

Also, adds a relevant test for `get_runs` (int)

### CODE REVIEW

**Comment by effigies** [comment]
@adelavega: 307aa37f66c034ae5c7d070a1c59edb9a1af2ac2 fixes the tests for me, when combined with the latest push to INCF/pybids#236.

I can push to your branch, or you can cherry-pick, but I didn't want to push in case you had some unpushed changes I might conflict with.

**Comment by tyarkoni** [comment]
LGTM, but will wait for @effigies's commit (which also looks good) to be added before merging.

**Comment by effigies** [comment]
Pushed my commit and a test last night. And tested downstream on FitLins... Along with a few fixups to handle unrelated changes, I'm able to fully run the test bundles we've been working with.

**Comment by adelavega** [comment]
Awesome. LGTM!

**Pull request merged**
