### PR TITLE
BF: make include/exclude judgement on relative path if path under the .root

### LINKED ISSUE #47: would fail to work on bids datasets which have a directory starting with . somewhere in their paths
Originally (https://github.com/datalad/datalad/issues/2150) I thought that the issue is symlinked directory somewhere in the path, so was trying to figure out where path `realpath`-ing is happening... long story short that apparently the issue with my `TMPDIR=/home/yoh/.tmp` (which is a symlink to `/tmp`) is having that `.tmp/` in the path since ATM https://github.com/INCF/pybids/blob/master/bids/grabbids/config/bids.json#L4 leads to exclusion of the paths which have it anywhere within their path.

I wondered -- may be  the relative path under the dataset root could be considered instead of the full path? (will submit a tentative fix in this vein)

### PR DESCRIPTION
**Pull request by yarikoptic**
Fixes #47 (and https://github.com/datalad/datalad/issues/2150)

TODO:
- [x] test

### CODE REVIEW

**Comment by tyarkoni** [comment]
No, I guess I never got around to implementing codecov. Will try to get to it soon, thanks for the reminder.

**Comment by tyarkoni** [comment]
This looks fine to me, but could your problem be solved by setting `absolute_paths=False` in the initializer? I haven't thought this through, just making sure that the new behavior doesn't mess with the intent of that argument.

**Comment by yarikoptic** [comment]
well, ... although on one hand -- may be, but instructing to convert all paths into absolute paths is a bit different. E.g. I might want to resort to default `absolute_paths=True` if I am changing directories from time to time and thus want to be able to provide relative paths and rely on grabbit to convert them to full paths for me (which I would assume while reading its docstring) and return full paths so I do not have to rely on knowing my curdir etc.

But I do not even see that setting used or stored anywhere besides
```python
self.root = abspath(path) if absolute_paths else path
```
and similarly in other derived constructors.  So ATM it is more "convert root path into an absolute path" setting, not what it really says in the docstring IMHO.  If there is some decision making is done based on either root is an absolute path (didn't check),  that is still different since I could have provided an absolute path for root. and have this one set to False to the same effect. So IMHO something should be done about this argument to make it live to its promise ;-)  or have I missed some point/code?

My changes reflect more of the analysis of those paths with the config/schema regular expressions, and not necessarily what is returned or what path is stored. I wonder, when do you see it meaningful to match path components in the parent  directories outside of the `root` path?   or did you envision Layout somehow dynamically react/check whenever I do not provide absolute path to root, set `absolute_paths=False` and start hopping directories? (it was not a "joke/pun" -- although might sound like one -- may be that was an intended use case somehow and I am just missing the point)

**Comment by tyarkoni** [comment]
I'm revisiting this issue as part of addressing #57, and I've decided I don't really like the current implementation of inclusion/exclusion checking, which changes the behavior depending on whether the file is underneath the `Layout` root. For one thing, it won't work going forward, because I'm taking away the project-wide root in favor of `Domain`-specific ones. But the bigger issue is that the behavior is currently unpredictable.

I propose that we split up the `include` directive into separate `include_files` and `include_dirs` directives (and the same for `exclude`). The former will search only the basenames; the latter will search only the dirnames. This will also have the secondary benefit of improving efficiency, since we'll be able to prune branches from the tree earlier, instead of having to scan every file. Any objections, @yarikoptic?

**Comment by yarikoptic** [comment]
Hi @tyarkoni , thank you for the update! I guess we with @mih should try it out with the fresh grabbit master.  Cheers!

**Pull request merged**
