### PR TITLE
ENH: Manage version with versioneer

### PR DESCRIPTION
**Pull request by effigies**
Versioneer gives you versions from the latest tag. So if I `pip install -e .` this branch:

```Shell
$ python -c 'import grabbit; print(grabbit.__version__)'
0.1.2+1.g4191f84
```

### CODE REVIEW

**Comment by effigies** [comment]
I've also tested this with `sdist` builds when creating a local `0.1.3` tag. That worked fine for me.

**Comment by effigies** [comment]
@oesteban can you have a quick look to make sure I did this correctly?

**Comment by effigies** [comment]
WRT that last question, I was able to move to `grabbit/external/versioneer.py` and change the `setup.py` import to `from grabbit.external import versioneer`. I'm not sure if there's value in having versioneer accessible from within grabbit, but I think it's doable. Let me know if you want me to push that commit.

**Comment by tyarkoni** [comment]
It's not a big deal either way, but I think I'd prefer it that way(i.e., in `external/`) just for organizational purposes. I don't expect it will ever be called from anywhere else in the code, but that's fine.

**Comment by effigies** [comment]
Hmm. That's causing this warning:

```Shell
$ python setup.py sdist      
Warning: build in /Users/markiewicz/Projects/grabbit/grabbit/external is using versioneer.py from /Users/markiewicz/Projects/grabbit/versioneer.py
...

Not sure if that's a problem.

**Comment by tyarkoni** [comment]
Weird. Okay let's just scratch that commit and keep it in the root

**Comment by tyarkoni** [comment]
Thanks!

**Pull request merged**
